name: build

on: 
  push:
    branches:
      - develop

jobs:
  build:
 
    # using Ubuntu
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '14.x'
 
    - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
 
    - name: NPM install
      run: npm install

    - name: NPM install angular cli
      run: npm install -g @angular/cli > /dev/null

    - name: NG build
      run: ng build --prod

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/upcloud.key
        chmod 600 ~/.ssh/upcloud.key
        cat >>~/.ssh/config <<END
        Host upcloud
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/upcloud.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.HOST }}

    - name: RSYNC dist/redisa-frontend
      run: rsync -azP --delete dist/redisa-frontend/./ upcloud:/home/cabu/redisa-front/public/.

    - name: ssh build-docker
      run: ssh upcloud 'sh /home/cabu/redisa-front/build-docker.sh'
